import React,{useEffect,useMemo,useRef,useState}from"react";
import{marked}from"marked";
import{jsPDF}from"jspdf";
import{Edit,Save,BookOpen,Download,FileText,X,Bold,Italic,Heading,List,ListOrdered,Quote,Code,Link as LinkIcon,Trash2,Table2}from"lucide-react";
import MarkdownEditor from"../MarkdownEditor.jsx";

const themes={beige:{page:"bg-[#F5F2EB] text-[#202122]",toolbar:"bg-neutral-100/50",input:"text-neutral-800",sidebar:"bg-neutral-100/30",card:"bg-white",dropdown:"bg-white",hover:"hover:bg-neutral-100",active:"bg-neutral-100",muted:"text-neutral-500",border:"border-neutral-300",buttonHover:"hover:bg-neutral-200",status:"bg-[#EAE5DB]"},wikipedia:{page:"bg-[#F8F9FA] text-[#202122]",toolbar:"bg-neutral-100/50",input:"text-[#202122]",sidebar:"bg-neutral-100/30",card:"bg-white",dropdown:"bg-white",hover:"hover:bg-neutral-100",active:"bg-neutral-100",muted:"text-neutral-500",border:"border-neutral-300",buttonHover:"hover:bg-neutral-200",status:"bg-white"},charcoal:{page:"bg-neutral-900 text-neutral-100",toolbar:"bg-neutral-900",input:"text-neutral-100",sidebar:"bg-neutral-900",card:"bg-neutral-800",dropdown:"bg-neutral-800",hover:"hover:bg-neutral-800",active:"bg-neutral-800",muted:"text-neutral-400",border:"border-neutral-700",buttonHover:"hover:bg-neutral-800",status:"bg-neutral-900"}};

export default function Editor({note,newNoteId,onSaveNote,onDeleteNote,notesPool=[],fontSize,setFontSize,onNavigateToNote,onCloseNote,articleCount=0,folderCount=0,subfolderCount=0,writingSince="",breadcrumb="",theme="beige"}){
 const c=themes[theme]||themes.beige;const ref=useRef(null);const[editing,setEditing]=useState(false);const[title,setTitle]=useState("");const[body,setBody]=useState("");const[suggest,setSuggest]=useState(null);const[table,setTable]=useState(false);const[rows,setRows]=useState(3);const[cols,setCols]=useState(3);const[header,setHeader]=useState(true);
 useEffect(()=>{if(!note)return;setTitle(note.title||"");setBody(note.body||"");setEditing(false);setSuggest(null)},[note?.id]);
 useEffect(()=>{if(note&&newNoteId===note.id){setEditing(true);requestAnimationFrame(()=>ref.current?.focus())}},[note?.id,newNoteId]);
 useEffect(()=>{if(typeof window!=="undefined"&&setFontSize)setFontSize(window.matchMedia("(max-width:639px)").matches?14:15)},[setFontSize]);
 const metrics=useMemo(()=>{const x=String(body||"");return{words:x.trim()?x.trim().split(/\s+/).length:0,characters:x.length,paragraphs:x.split(/\n\s*\n/).filter(x=>x.trim()).length,headings:(x.match(/^#{1,6}\s+.+$/gm)||[]).length,wikiLinks:(x.match(/\[\[[^\]]+\]\]/g)||[]).length}},[body]);
 const backlinks=useMemo(()=>notesPool.filter(n=>n.id!==note?.id&&note?.title&&String(n.body||"").toLowerCase().includes(`[[${note.title.toLowerCase()}]]`)),[notesPool,note?.id,note?.title]);
 const change=v=>{setBody(v);const m=v.match(/\[\[([^\]]*)$/);if(!m){setSuggest(null);return}const list=notesPool.filter(n=>n.id!==note?.id&&n.title?.toLowerCase().startsWith(m[1].toLowerCase()));setSuggest(list.length?{list,index:0}:null)};
 const insertWiki=t=>{const m=body.match(/\[\[[^\]]*$/);if(!m)return;setBody(body.slice(0,-m[0].length)+`[[${t}]]`);setSuggest(null);requestAnimationFrame(()=>ref.current?.focus())};
 const pdf=()=>{const p=new jsPDF({unit:"mm",format:"a4"});let y=20;p.setFont("helvetica");p.setFontSize(11);for(const line of p.splitTextToSize(`${title||"Untitled Note"}\n\n${body}`,174)){if(y>280){p.addPage();y=20}p.text(line,18,y);y+=6}p.save(`${(title||"Untitled Note").replace(/[<>:"/\\|?*]/g,"_").slice(0,120)}.pdf`)};
 if(!note)return <div className={`h-full w-full flex items-center justify-center ${c.page}`}><div className="text-center"><BookOpen size={34} className="mx-auto mb-5 text-neutral-400"/><h1 className="text-3xl mb-3">{new Date().getHours()<12?"Good morning!":new Date().getHours()<18?"Good afternoon!":"Good evening!"}</h1><p className={c.muted}>Glimpse of your digital brain</p><div className="mt-10 flex justify-center gap-8"><span><b>{articleCount}</b><small className="block text-neutral-400">Articles</small></span><span><b>{folderCount}</b><small className="block text-neutral-400">Folders</small></span><span><b>{subfolderCount}</b><small className="block text-neutral-400">Subfolders</small></span></div>{writingSince&&<p className="mt-8 text-xs text-neutral-400">Writing since {writingSince}</p>}</div></div>;
 const save=async()=>{await onSaveNote?.(note.id,title,body);setEditing(false)};
 return <div className={`relative flex-1 min-h-0 flex flex-col h-full overflow-hidden ${c.page}`}>
  <header className={`shrink-0 border-b ${c.border} ${c.toolbar}`}><div className="flex flex-col md:flex-row md:items-center md:justify-between gap-2 px-4 py-2 md:px-6"><div className="min-w-0 overflow-x-auto whitespace-nowrap text-xs text-neutral-500">ArchiWiki{breadcrumb?` > ${breadcrumb.split("/").map(x=>x.trim()).filter(Boolean).join(" > ")}`:""} &gt; {title||"Untitled"}</div><div className="flex items-center gap-2 shrink-0"><span className="text-xs hidden sm:inline">Size:</span><input type="range" min="12" max="24" value={Number(fontSize)||15} onChange={e=>setFontSize?.(Number(e.target.value))} className="w-20"/><button onClick={pdf} title="Download PDF" className={`p-1.5 ${c.buttonHover} rounded`}><Download size={14}/></button>{editing&&<button onClick={()=>onDeleteNote?.(note.id)} className="p-1.5 text-red-600 rounded hover:bg-red-50"><Trash2 size={14}/></button>}<button onClick={editing?save:()=>{setEditing(true);requestAnimationFrame(()=>ref.current?.focus())}} className="px-3 py-1.5 bg-neutral-900 text-white rounded text-xs font-semibold">{editing?<><Save size={12} className="inline mr-1"/>Save</>:<><Edit size={12} className="inline mr-1"/>Edit</>}</button><button onClick={onCloseNote} className={`p-1.5 ${c.buttonHover} rounded`}><X size={16}/></button></div></div></header>
  <div className="flex-1 min-h-0 flex overflow-hidden pb-[58px] md:pb-0"><main className="flex-1 min-h-0 min-w-0 flex flex-col p-8 max-md:p-4 overflow-y-auto" style={{fontSize:`${Number(fontSize||15)}px`}}>
   {editing?<div className="flex-1 min-h-0 flex flex-col gap-3 relative"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Title your note" className={`w-full bg-transparent border-b ${c.border} pb-2 focus:outline-none text-2xl font-bold`}/><div className={`flex gap-1 border-b ${c.border} pb-2 overflow-x-auto`}><button onClick={()=>ref.current?.toggleBold()} className={`p-1.5 ${c.buttonHover}`}><Bold size={14}/></button><button onClick={()=>ref.current?.toggleItalic()} className={`p-1.5 ${c.buttonHover}`}><Italic size={14}/></button><button onClick={()=>ref.current?.toggleHeading(2)} className={`p-1.5 ${c.buttonHover}`}><Heading size={14}/></button><button onClick={()=>ref.current?.toggleBulletList()} className={`p-1.5 ${c.buttonHover}`}><List size={14}/></button><button onClick={()=>ref.current?.toggleOrderedList()} className={`p-1.5 ${c.buttonHover}`}><ListOrdered size={14}/></button><button onClick={()=>ref.current?.toggleBlockquote()} className={`p-1.5 ${c.buttonHover}`}><Quote size={14}/></button><button onClick={()=>ref.current?.toggleCode()} className={`p-1.5 ${c.buttonHover}`}><Code size={14}/></button><button onClick={()=>setTable(true)} className={`p-1.5 ${c.buttonHover}`}><Table2 size={14}/></button><button onClick={()=>ref.current?.setLink("https://")} className={`p-1.5 ${c.buttonHover}`}><LinkIcon size={14}/></button></div><div className="flex-1 min-h-0"><MarkdownEditor ref={ref} value={body} onChange={change} editable className={c.input}/></div>{suggest&&<div className={`absolute z-50 top-24 left-4 w-64 ${c.dropdown} border ${c.border} rounded shadow-lg p-1 text-xs`}>{suggest.list.map((n,i)=><button key={n.id} onMouseDown={e=>{e.preventDefault();insertWiki(n.title)}} className={`w-full text-left px-3 py-1.5 rounded ${i===suggest.index?c.active:c.hover}`}><FileText size={12} className="inline mr-1"/>{n.title}</button>)}</div>}</div>:<article onClick={e=>{const x=e.target.closest?.(".wiki-link");if(x?.dataset.noteId)onNavigateToNote?.(x.dataset.noteId)}} className="wiki-content w-full max-w-4xl mr-auto"><h1 className="text-2xl font-bold border-b border-neutral-300 pb-3 mb-5">{title||"Untitled Note"}</h1><div dangerouslySetInnerHTML={{__html:render(body,notesPool)}}/></article>}
  </main><aside className={`w-56 border-l ${c.border} ${c.sidebar} p-4 max-lg:hidden`}><h4 className="font-bold uppercase tracking-wider text-[10px] text-neutral-500">Backlinks ({backlinks.length})</h4><div className="mt-3 space-y-2">{backlinks.map(n=><button key={n.id} onClick={()=>onNavigateToNote?.(n.id)} className={`w-full text-left p-2 border ${c.border} ${c.card} rounded ${c.buttonHover}`}><b className="block truncate">{n.title}</b><span className="block truncate text-[10px] text-neutral-500">{n.body}</span></button>)}</div></aside></div>
  <footer className={`absolute bottom-0 left-0 right-0 border-t ${c.border} ${c.status} text-[11px] text-neutral-500 px-4 py-2 overflow-x-auto`}><div className="min-w-max flex gap-4">Words: <b>{metrics.words}</b> Characters: <b>{metrics.characters}</b> Paragraphs: <b>{metrics.paragraphs}</b> Headings: <b>{metrics.headings}</b> Wiki Links: <b>{metrics.wikiLinks}</b><span className="ml-auto">Status: <b>Encrypted AES-256</b></span></div></footer>
  {table&&<div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 p-4" onMouseDown={e=>e.target===e.currentTarget&&setTable(false)}><div className={`w-full max-w-sm rounded border p-5 shadow-xl ${c.card}`}><h2 className="font-semibold">Insert table</h2><div className="grid grid-cols-2 gap-3 mt-4"><label className="text-xs">Rows<input type="number" min="1" max="50" value={rows} onChange={e=>setRows(Math.max(1,Math.min(50,Number(e.target.value)||1)))} className="w-full mt-1 border rounded p-1 bg-transparent"/></label><label className="text-xs">Columns<input type="number" min="1" max="20" value={cols} onChange={e=>setCols(Math.max(1,Math.min(20,Number(e.target.value)||1)))} className="w-full mt-1 border rounded p-1 bg-transparent"/></label></div><label className="flex gap-2 mt-4 text-sm"><input type="checkbox" checked={header} onChange={e=>setHeader(e.target.checked)}/>Header row</label><div className="flex justify-end gap-2 mt-5"><button onClick={()=>setTable(false)} className="px-3 py-1.5 text-xs">Cancel</button><button onClick={()=>{ref.current?.insertTable(rows,cols,header);setTable(false)}} className="px-3 py-1.5 bg-neutral-900 text-white rounded text-xs">Insert</button></div></div></div>}
 </div>
}
function render(raw,notes){const links=[];const safe=String(raw||"").replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g,(_,t,l)=>{const i=links.length;links.push({t:t.trim(),l:(l||t).trim()});return`WIKILINKPLACEHOLDER${i}WIKILINKPLACEHOLDER`});let html=marked.parse(safe,{breaks:true});return html.replace(/WIKILINKPLACEHOLDER(\d+)WIKILINKPLACEHOLDER/g,(_,i)=>{const x=links[Number(i)],n=notes.find(a=>a.title?.trim().toLowerCase()===x.t.toLowerCase());return n?`<span class="wiki-link" data-note-id="${n.id}">${esc(x.l)}</span>`:`<span class="wiki-link-missing">${esc(x.l)}</span>`})}
function esc(x){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
