import React,{useEffect,useState}from"react";
import{signInWithEmailAndPassword,onAuthStateChanged,signOut}from"firebase/auth";
import{collection,setDoc,onSnapshot,query,orderBy,serverTimestamp,doc,getDoc,updateDoc}from"firebase/firestore";
import{auth,db}from"../firebase";
import{Wrench,LogOut}from"lucide-react";

const maintenanceRef=doc(db,"adminMetrics","maintenance");
const gen=()=>{const a="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",v=new Uint32Array(12);crypto.getRandomValues(v);return Array.from(v,x=>a[x%a.length]).join("")};
const timeout=(p,m=8000)=>Promise.race([p,new Promise((_,r)=>setTimeout(()=>r(new Error("Administrator access check timed out.")),m))]);

export default function InviteAdmin(){
 const[user,setUser]=useState(null),[authorized,setAuthorized]=useState(false),[checking,setChecking]=useState(true),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[invites,setInvites]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState(""),[creating,setCreating]=useState(false),[loggingIn,setLoggingIn]=useState(false),[newToken,setNewToken]=useState(""),[maintenance,setMaintenance]=useState(false),[savingMaintenance,setSavingMaintenance]=useState(false);

 useEffect(()=>{let mounted=true;return onAuthStateChanged(auth,async u=>{if(!mounted)return;setUser(u);setAuthorized(false);if(!u){setChecking(false);return}try{const s=await timeout(getDoc(doc(db,"admins",u.uid)));if(s.exists()&&s.data()?.enabled===true){setAuthorized(true)}else{await signOut(auth);setUser(null);setError("This Firebase account is not authorized as an administrator.")}}catch(e){setError(e?.message||"Unable to verify administrator access.")}finally{if(mounted)setChecking(false)}})},[]);
 useEffect(()=>{if(!authorized){setInvites([]);return}return onSnapshot(query(collection(db,"pendingInvites"),orderBy("createdAt","desc")),s=>setInvites(s.docs.map(d=>({id:d.id,...d.data()}))),e=>setError(e?.message||"Unable to load invitations.")},[authorized]);
 useEffect(()=>{if(!authorized)return;return onSnapshot(maintenanceRef,async s=>{if(!s.exists()){try{await setDoc(maintenanceRef,{inMaintenance:false,updatedAt:Date.now()},{merge:true})}catch(e){console.error(e)}setMaintenance(false);return}setMaintenance(s.data()?.inMaintenance===true)},e=>setError("Unable to read maintenance status. Check Firestore rules."))},[authorized]);

 const login=async e=>{e.preventDefault();if(loggingIn)return;setLoggingIn(true);setError("");try{const c=await signInWithEmailAndPassword(auth,email.trim().toLowerCase(),password);const s=await timeout(getDoc(doc(db,"admins",c.user.uid)));if(!s.exists()||s.data()?.enabled!==true){await signOut(auth);throw new Error("This account is not authorized as an administrator.")}setUser(c.user);setAuthorized(true);setEmail("");setPassword("")}catch(e){setError(e?.message||"Unable to sign in.")}finally{setLoggingIn(false)}};
 const toggle=async()=>{if(savingMaintenance)return;setSavingMaintenance(true);setError("");try{await setDoc(maintenanceRef,{inMaintenance:!maintenance,updatedAt:Date.now()},{merge:true})}catch(e){setError(e?.message||"Unable to change maintenance mode. Check Firestore rules.")}finally{setSavingMaintenance(false)}};
 const create=async()=>{if(creating)return;setCreating(true);setError("");try{const token=gen();await setDoc(doc(db,"pendingInvites",token),{token,status:"available",used:false,claimId:null,claimedAt:null,usedBy:null,usedEmail:null,usedAt:null,createdAt:serverTimestamp(),createdBy:user.uid});setNewToken(token);setMessage("Invitation created: "+token)}catch(e){setError(e?.message||"Unable to create invitation.")}finally{setCreating(false)}};
 const link=t=>`${location.origin}/?invite=${encodeURIComponent(t)}`;
 const copy=async(t)=>{try{await navigator.clipboard.writeText(link(t));setMessage("Invitation link copied.");setError("")}catch{setError("Unable to copy the invitation link.")}};
 const revoke=async i=>{const t=i.token||i.id;if(!t||i.status==="used"||i.status==="revoked"||!confirm("Revoke invitation "+t+"?"))return;try{await updateDoc(doc(db,"pendingInvites",t),{status:"revoked",revoked:true,revokedAt:serverTimestamp(),revokedBy:user.uid});setMessage("Invitation revoked.");setError("")}catch(e){setError(e?.message||"Unable to revoke invitation.")}};
 const logout=async()=>{await signOut(auth);setUser(null);setAuthorized(false);setInvites([])};
 const date=v=>{if(!v)return"—";try{const d=typeof v.toDate==="function"?v.toDate():new Date(v);return d.toLocaleString()}catch{return"—"}};

 if(checking)return <div className="min-h-screen flex items-center justify-center bg-[#F5F2EB]"><div className="bg-white border border-neutral-300 rounded p-7 shadow-sm text-center"><b>ArchiWiki Administration</b><p className="text-xs text-neutral-500 mt-2">Checking administrator access…</p></div></div>;
 if(!user||!authorized)return <div className="min-h-screen flex items-center justify-center bg-[#F5F2EB] p-6"><form onSubmit={login} className="w-full max-w-sm bg-white border border-neutral-300 rounded shadow-sm p-7 space-y-4"><h1 className="text-xl font-bold text-center">ArchiWiki Administration</h1><p className="text-xs text-neutral-500 text-center">Private administrator access</p><input type="email" required placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full border border-neutral-300 rounded px-3 py-2 text-sm"/><input type="password" required placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full border border-neutral-300 rounded px-3 py-2 text-sm"/>{error&&<p className="p-3 bg-red-50 border border-red-200 rounded text-xs text-red-700">{error}</p>}<button disabled={loggingIn} className="w-full py-2 bg-neutral-900 text-white rounded text-sm">{loggingIn?"Signing in…":"Sign in"}</button></form></div>;

 return <div className="min-h-screen bg-[#F5F2EB] text-neutral-900 p-6"><div className="max-w-5xl mx-auto">
  <header className="flex items-center justify-between mb-8"><div><h1 className="text-2xl font-bold">Invitation Manager</h1><p className="text-xs text-neutral-500 mt-1">ArchiWiki administrator</p></div><div className="flex items-center gap-2">
   <button onClick={toggle} disabled={savingMaintenance} aria-pressed={maintenance} title={maintenance?"Maintenance mode is ON":"Maintenance mode is OFF"} className="inline-flex items-center gap-2 rounded-md border border-neutral-300 bg-white px-2.5 py-1.5 text-xs text-neutral-700 hover:bg-neutral-50 disabled:opacity-50"><Wrench size={13}/><span>Maintenance</span><span className={"h-2 w-2 rounded-full "+(maintenance?"bg-amber-500":"bg-green-600")}/></button>
   <button onClick={logout} title="Sign out" className="inline-flex items-center gap-1.5 rounded-md border border-neutral-300 bg-white px-2.5 py-1.5 text-xs text-neutral-600 hover:bg-neutral-50"><LogOut size={13}/>Sign out</button>
  </div></header>
  {error&&<div className="mb-4 rounded border border-red-200 bg-red-50 px-4 py-2.5 text-xs text-red-700">{error}</div>}
  {message&&<div className="mb-4 rounded border border-green-200 bg-green-50 px-4 py-2.5 text-xs text-green-700">{message}{newToken&&<button onClick={()=>copy(newToken)} className="ml-3 underline">Copy link</button>}</div>}
  <div className="bg-white border border-neutral-300 rounded p-6 mb-6"><h2 className="font-semibold mb-2">Create invitation</h2><p className="text-xs text-neutral-500 mb-4">Generate a single-use invitation token.</p><button onClick={create} disabled={creating} className="px-4 py-2 bg-neutral-900 text-white rounded text-sm">{creating?"Creating…":"Generate Invite"}</button></div>
  <div className="bg-white border border-neutral-300 rounded overflow-hidden"><div className="p-5 border-b border-neutral-200"><h2 className="font-semibold">Invitations</h2><p className="text-xs text-neutral-500 mt-1">{invites.length} invitation{invites.length===1?"":"s"}</p></div>
  {invites.length===0?<div className="p-8 text-center text-sm text-neutral-500">No invitations yet.</div>:<div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b text-left"><th className="p-4">Code</th><th className="p-4">Status</th><th className="p-4">Created</th><th className="p-4">Used by</th><th className="p-4">Used at</th><th className="p-4">Actions</th></tr></thead><tbody>{invites.map(i=>{const t=i.token||i.id,s=i.status||(i.used?"Used":"Available");return <tr key={i.id} className="border-b border-neutral-100"><td className="p-4 font-mono">{t}</td><td className="p-4">{s}</td><td className="p-4 text-neutral-500">{date(i.createdAt)}</td><td className="p-4">{i.usedEmail||"—"}</td><td className="p-4 text-neutral-500">{date(i.usedAt)}</td><td className="p-4">{s!=="used"&&s!=="revoked"?<button onClick={()=>revoke(i)} className="text-red-600 hover:underline">Revoke</button>:"—"}</td></tr>})}</tbody></table></div>}</div>
 </div></div>;
}
